/*
 * docgen — writes docs/CONFIGURATION.md from the property registry.
 *
 * The registry in src/spec.c is the single source of truth for what a widget
 * can be told to do. Generating the reference from it means the docs cannot
 * drift from the parser: add a key there and it shows up here.
 *
 *   docgen <output.md>          write the reference
 *   docgen <output.md> --check  exit 1 if the file on disk is out of date
 */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "spec.h"
#include "style.h"

static const char* KindName(int kind) {
    switch (kind) {
        case PK_INT:   return "integer";
        case PK_FLOAT: return "number";
        case PK_COLOR: return "colour";
        case PK_BOOL:  return "true / false";
        case PK_ENUM:  return "choice";
        case PK_FONT:  return "font name";
        case PK_FILE:  return "path";
        default:       return "text";
    }
}

static void WriteTypes(FILE* out, unsigned int types) {
    bool all = true;
    for (int t = 0; t < WIDGET__COUNT; t++)
        if (!(types & TYPE_BIT(t))) all = false;

    if (all) { fputs("all", out); return; }

    bool first = true;
    for (int t = 0; t < WIDGET__COUNT; t++) {
        if (!(types & TYPE_BIT(t))) continue;
        fprintf(out, "%s%s", first ? "" : ", ", Spec_TypeName(t));
        first = false;
    }
}

/* Enum choices are stored pipe-separated; "@presets" expands at runtime. */
static void WriteChoices(FILE* out, const PropDef* prop) {
    if (prop->kind != PK_ENUM || !prop->options) {
        fprintf(out, "%s", KindName(prop->kind));
        return;
    }
    if (strcmp(prop->options, "@presets") == 0) {
        int count = 0;
        const StylePreset* presets = Style_Presets(&count);
        for (int i = 0; i < count; i++)
            fprintf(out, "%s`%s`", i ? ", " : "", presets[i].name);
        return;
    }

    char buffer[512];
    strncpy(buffer, prop->options, sizeof(buffer) - 1);
    buffer[sizeof(buffer) - 1] = '\0';

    char* context = NULL;
    bool first = true;
    for (char* token = strtok_s(buffer, "|", &context); token;
         token = strtok_s(NULL, "|", &context)) {
        fprintf(out, "%s`%s`", first ? "" : ", ", token);
        first = false;
    }
}

static void WriteReference(FILE* out) {
    fputs("<!-- Generated by tools/docgen.c from the property registry in\n"
          "     src/spec.c. Run `build.bat tools && bin\\docgen docs\\CONFIGURATION.md`\n"
          "     after changing a key; do not edit this file by hand. -->\n\n",
          out);

    fputs("# Configuration reference\n\n"
          "Widgets live in `config/widgets.ini`. Each `[section]` is one widget; the\n"
          "section name is a label you choose, and it is what the settings editor\n"
          "shows in its list.\n\n"
          "```ini\n"
          "[clock]\n"
          "type=clock\n"
          "preset=midnight\n"
          "anchor=top_right\n"
          "x=-60\n"
          "y=64\n"
          "width=360\n"
          "height=156\n"
          "font_size=66\n"
          "```\n\n"
          "Only `type` is required. Every other key falls back to its default, and a\n"
          "`preset` supplies a themed set of defaults that individual keys override.\n\n"
          "Colours are hex `AARRGGBB`. `RRGGBB`, `#RGB` and `#ARGB` are also accepted\n"
          "and are expanded to full opacity where no alpha is given. An alpha of `00`\n"
          "means \"off\" for effects such as shadow, glow and outline.\n\n", out);

    int count = 0;
    const PropDef* props = Spec_Properties(&count);

    for (int group = 0; group < PG__COUNT; group++) {
        bool any = false;
        for (int i = 0; i < count; i++)
            if (props[i].group == group) { any = true; break; }
        if (!any) continue;

        fprintf(out, "## %s\n\n", Spec_GroupName(group));
        fputs("| Key | Applies to | Values | Default | Description |\n", out);
        fputs("| --- | --- | --- | --- | --- |\n", out);

        for (int i = 0; i < count; i++) {
            const PropDef* prop = &props[i];
            if (prop->group != group) continue;

            fprintf(out, "| `%s` | ", prop->key);
            WriteTypes(out, prop->types);
            fputs(" | ", out);
            WriteChoices(out, prop);
            fprintf(out, " | %s%s%s | %s |\n",
                    prop->def[0] ? "`" : "",
                    prop->def[0] ? prop->def : "(none)",
                    prop->def[0] ? "`" : "",
                    prop->help ? prop->help : "");
        }
        fputc('\n', out);
    }

    fputs("## Style presets\n\n"
          "`preset` applies a bundle of the keys above before any of your own are\n"
          "read, so you can start from a theme and change just the parts you want.\n\n"
          "| Preset | Looks like |\n| --- | --- |\n", out);

    int presetCount = 0;
    const StylePreset* presets = Style_Presets(&presetCount);
    for (int i = 0; i < presetCount; i++)
        fprintf(out, "| `%s` | %s |\n", presets[i].name, presets[i].description);

    fputs("\n## Time and date patterns\n\n"
          "`time_format` and `date_format` take .NET-style tokens. Everything that is\n"
          "not a token is copied through; use `\\` to escape one character and\n"
          "`'single quotes'` for a literal run.\n\n"
          "| Token | Meaning | Example |\n| --- | --- | --- |\n"
          "| `H` / `HH` | Hour, 24-hour | `7` / `07` |\n"
          "| `h` / `hh` | Hour, 12-hour | `7` / `07` |\n"
          "| `m` / `mm` | Minute | `5` / `05` |\n"
          "| `s` / `ss` | Second | `9` / `09` |\n"
          "| `f` | Tenths of a second | `4` |\n"
          "| `t` / `tt` | AM/PM designator | `P` / `PM` |\n"
          "| `d` / `dd` | Day of month | `3` / `03` |\n"
          "| `ddd` / `dddd` | Weekday name | `Tue` / `Tuesday` |\n"
          "| `M` / `MM` | Month number | `9` / `09` |\n"
          "| `MMM` / `MMMM` | Month name | `Sep` / `September` |\n"
          "| `yy` / `yyyy` | Year | `26` / `2026` |\n\n"
          "Weekday, month and AM/PM names come from the current Windows locale.\n\n"
          "```ini\n"
          "time_format=h:mm tt\n"
          "date_format=dddd, d MMMM\n"
          "date_format=ddd d MMM 'in' yyyy\n"
          "```\n\n"
          "## Anchors\n\n"
          "`x` and `y` are an offset from the `anchor` point on the target monitor,\n"
          "not absolute desktop coordinates. A widget anchored `top_right` with\n"
          "`x=-60` sits 60px in from the right edge and stays there when the screen\n"
          "resolution changes.\n\n"
          "`monitor` selects a display by index; `-1` means the primary one.\n", out);
}

int main(int argc, char** argv) {
    if (argc < 2) {
        fprintf(stderr, "usage: docgen <output.md> [--check]\n");
        return 2;
    }
    const char* path = argv[1];
    bool check = (argc > 2 && strcmp(argv[2], "--check") == 0);

    if (!check) {
        FILE* out = fopen(path, "wb");
        if (!out) {
            fprintf(stderr, "docgen: cannot write %s\n", path);
            return 1;
        }
        WriteReference(out);
        fclose(out);
        printf("docgen: wrote %s\n", path);
        return 0;
    }

    /* --check renders to a temp file and diffs it against what is on disk. */
    char tempDir[MAX_PATH], tempFile[MAX_PATH];
    GetTempPathA(MAX_PATH, tempDir);
    GetTempFileNameA(tempDir, "lwd", 0, tempFile);

    FILE* out = fopen(tempFile, "wb");
    if (!out) { fprintf(stderr, "docgen: cannot write a temp file\n"); return 1; }
    WriteReference(out);
    fclose(out);

    FILE* a = fopen(path, "rb");
    FILE* b = fopen(tempFile, "rb");
    int result = 0;

    if (!a) {
        fprintf(stderr, "docgen: %s does not exist\n", path);
        result = 1;
    } else {
        int ca, cb;
        do {
            ca = fgetc(a);
            cb = fgetc(b);
            if (ca != cb) {
                fprintf(stderr, "docgen: %s is out of date -- regenerate it\n", path);
                result = 1;
                break;
            }
        } while (ca != EOF);
    }

    if (a) fclose(a);
    if (b) fclose(b);
    DeleteFileA(tempFile);

    if (result == 0) printf("docgen: %s is up to date\n", path);
    return result;
}
